name: .NET 5 CI
on:
  push:
    branches:
      - develop # or the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET 5 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101' # Check for latest at link at .NET 5 download page
      - run: dotnet publish BANKFE -c Release -o deploy
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.5.3
        with:
          local: /home/runner/work/BANKFE/BANKFE/deploy/
          remote: ${{ secrets.REMOTE_TARGET }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: sudo systemctl restart Web.service
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}